# Generated by Django 5.1.4 on 2024-12-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In process', 'In process'), ('Failed', 'Failed')], default=('In process', 'In process'), max_length=10),
        ),
    ]
